# Generated by Django 3.2.17 on 2023-04-12 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='depId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ajapp.department'),
            preserve_default=False,
        ),
    ]
