# Generated by Django 3.2.17 on 2023-04-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0002_subject_depid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ajapp.login'),
            preserve_default=False,
        ),
    ]
