# Generated by Django 3.2.17 on 2023-05-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0003_student_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=90),
        ),
    ]
