# Generated by Django 3.2.17 on 2023-05-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0004_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendence', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapp.student')),
            ],
        ),
    ]
