# Generated by Django 3.2.17 on 2023-05-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0005_studentattendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='attendence',
            field=models.BooleanField(),
        ),
    ]
