# Generated by Django 3.2.17 on 2023-05-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0007_rename_studentattendence_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='studentAttendence',
        ),
    ]
