# Generated by Django 3.2.17 on 2023-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0008_rename_attendance_studentattendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='attendence',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
