# Generated by Django 3.2.17 on 2023-05-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0009_alter_studentattendence_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='attendence',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
